### ISSUE TITLE
Cannot get it working

### ISSUE THREAD

**Issue by fideldalmasso** [mistrza/Turing-CSS#1]
Hi!
Just installed this theme, but nothing seems to happen..
I copied the css, restarted the program and selected Turing from the popup :(

Should I do something else? Maybe I need to install some fonts.

Thanks!

**Comment by mistrza** [comment]
Hi!
The style uses `monospace` font if the main one is not found so this is not the problem.
I updated `README.me` to add installing instructions.

**Comment by mistrza** [comment]
Please update Typora and provide a screenshot.

**Comment by fideldalmasso** [comment]
Hi! I'm using Linux Mint. This is what I see:
![image](https://user-images.githubusercontent.com/39715777/57184260-6f685d00-6e8f-11e9-8a41-9401f3476f30.png)

**Comment by mistrza** [comment]
Have you tried to install other themes than mine? If so, do they work?
I will try the GNU/Linux version of Typora soon to test the feature.

**Comment by mistrza** [comment]
I tested the theme on two independent GNU/Linux devices and I cannot reproduce the bug.
